# GitHub Actions workflow for building and publishing the custom Docker image
# that this custom GitHub Action uses to run the necessary Python scripts.
name: Publish Docker Image

on:

  # Run on every commit to the primary branch.
  push:
    branches:
      - master
      - main

  # Run on every new release.
  release:
    types:
      - published

  # Run on every new tag.
  create:
    tags:
      - 'v*'

  # Allow running this workflow manually.
  workflow_dispatch:

jobs:

  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ## TODO: Add tagged releases to the workflow/build/image tags etc.
      - name: Build and Deploy
        uses: docker/build-push-action@v4
        with:
          # context: '{{ defaultContext }}:docker'
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          # tags: ghcr.io/didstopia/apt-repo-action:latest
          tags: ghcr.io/didstopia/apt-repo-action:bleeding
